export const datos_habitaciones= [
  {
    HabitacionDetalleId:1,
    nroHabitacion: 101,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:2,
    nroHabitacion: 102,
    nivel: "piso 1",
    estado:"En Mantenimiento",
  },
  {
    HabitacionDetalleId:3,
    nroHabitacion: 103,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:4,
    nroHabitacion: 104,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:5,
    nroHabitacion: 105,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:6,
    nroHabitacion: 106,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:7,
    nroHabitacion: 107,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:8,
    nroHabitacion: 108,
    nivel: "piso 1",
    estado:"En Mantenimiento",
  },
  {
    HabitacionDetalleId:9,
    nroHabitacion: 109,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:10,
    nroHabitacion: 110,
    nivel: "piso 1",
    estado:"activo",
  },
  {
    HabitacionDetalleId:11,
    nroHabitacion: 201,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:12,
    nroHabitacion: 202,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:13,
    nroHabitacion: 203,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:14,
    nroHabitacion: 204,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:15,
    nroHabitacion: 205,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:16,
    nroHabitacion: 206,
    nivel: "piso 2",
    estado:"En Mantenimiento",
  },
  {
    HabitacionDetalleId:17,
    nroHabitacion: 207,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:18,
    nroHabitacion: 208,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:19,
    nroHabitacion: 209,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:20,
    nroHabitacion: 210,
    nivel: "piso 2",
    estado:"activo",
  },
  {
    HabitacionDetalleId:21,
    nroHabitacion: 301,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:22,
    nroHabitacion: 302,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:23,
    nroHabitacion: 303,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:24,
    nroHabitacion: 304,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:25,
    nroHabitacion: 305,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:26,
    nroHabitacion: 306,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:27,
    nroHabitacion: 307,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:28,
    nroHabitacion: 308,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:29,
    nroHabitacion: 309,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:30,
    nroHabitacion: 310,
    nivel: "piso 3",
    estado:"activo",
  },
  {
    HabitacionDetalleId:31,
    nroHabitacion: 401,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:32,
    nroHabitacion: 402,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:33,
    nroHabitacion: 403,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:34,
    nroHabitacion: 404,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:35,
    nroHabitacion: 405,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:36,
    nroHabitacion: 406,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:37,
    nroHabitacion: 407,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:38,
    nroHabitacion: 408,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:39,
    nroHabitacion: 409,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:40,
    nroHabitacion: 410,
    nivel: "piso 4",
    estado:"activo",
  },
  {
    HabitacionDetalleId:41,
    nroHabitacion: 501,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:42,
    nroHabitacion: 502,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:43,
    nroHabitacion: 503,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:44,
    nroHabitacion: 504,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:45,
    nroHabitacion: 505,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:46,
    nroHabitacion: 506,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:47,
    nroHabitacion: 507,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:48,
    nroHabitacion: 508,
    nivel: "piso 5",
    estado:"activo",
  },
  {
    HabitacionDetalleId:49,
    nroHabitacion: 601,
    nivel: "piso 6",
    estado:"activo",
  },
  {
    HabitacionDetalleId:50,
    nroHabitacion: 602,
    nivel: "piso 6",
    estado:"activo",
  },
  {
    HabitacionDetalleId:51,
    nroHabitacion: 603,
    nivel: "piso 6",
    estado:"activo",
  },
  {
    HabitacionDetalleId:52,
    nroHabitacion: 604,
    nivel: "piso 6",
    estado:"activo",
  },
  {
    HabitacionDetalleId:53,
    nroHabitacion: 605,
    nivel: "piso 6",
    estado:"activo",
  },
  {
    HabitacionDetalleId:54,
    nroHabitacion: 606,
    nivel: "piso 7",
    estado:"activo",
  },
  {
    HabitacionDetalleId:55,
    nroHabitacion: 607,
    nivel: "piso 8",
    estado:"activo",
  },
  {
    HabitacionDetalleId:56,
    nroHabitacion: 608,
    nivel: "piso 9",
    estado:"activo",
  },
  {
    HabitacionDetalleId:57,
    nroHabitacion: 609,
    nivel: "piso 10",
    estado:"activo",
  },
  {
    HabitacionDetalleId:58,
    nroHabitacion: 610,
    nivel: "piso 11",
    estado:"activo",
  },
];
